//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alert
    {
        public int alert_id { get; set; }
        public int user_id { get; set; }
        public string alert_type { get; set; }
        public Nullable<System.DateTime> alert_time { get; set; }
        public bool email_sent { get; set; }
        public string details { get; set; }
    
        public virtual User User { get; set; }
    }
}
