//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Amortization
    {
        public int amortization_id { get; set; }
        public int installment_number { get; set; }
        public System.DateTime due_date { get; set; }
        public decimal remaining_balance { get; set; }
        public decimal principal { get; set; }
        public int loan_id { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public decimal payment_amount { get; set; }
        public Nullable<decimal> penalty_interest { get; set; }
    
        public virtual Loan Loan { get; set; }
    }
}
