//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int log_id { get; set; }
        public int user_id { get; set; }
        public string event_type { get; set; }
        public Nullable<System.DateTime> event_time { get; set; }
        public string ip_address { get; set; }
        public string description { get; set; }
    
        public virtual User User { get; set; }
    }
}
