//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Data
    {
        public int user_data_id { get; set; }
        public decimal salary { get; set; }
        public int family_load { get; set; }
        public string workplace { get; set; }
        public string housing_type { get; set; }
        public Nullable<decimal> rent_cost { get; set; }
        public int years_of_employment { get; set; }
        public byte employment_status { get; set; }
        public int user_id { get; set; }
    
        public virtual User User { get; set; }
    }
}
